array_layout = "Block"  # RFC.
chain_indent = "Block"  # Default.
closure_block_indent_threshold = -1
error_on_line_overflow = false
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_call_style = "Block"
fn_return_indent = "WithWhereClause"
match_block_trailing_comma = true
newline_style = "Unix"  # Default.
# Separate `std`, other crates, and `self` manually.
reorder_imports = false  # Default.
trailing_comma = "Vertical"  # Default.
where_style = "Rfc"  # RFC.

# This file is for =rustfmt-0.9.0 .
